public class ContactList {
    // GET ALL FROM CONTACTS.TXT

    // ADD NEW CONTACT TO CONTACTS.TXT

    // GET CONTACT BY NAME

    // DELETE CONTACT BY NAME

    //STRETCH GOAL, UPDATE CONTACT BY NAME?
}